# Generated by Django 3.1.1 on 2021-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='ad_pics'),
        ),
    ]
