# Generated by Django 3.1.2 on 2021-02-11 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='favorites',
        ),
    ]
