# Generated by Django 3.1.2 on 2021-01-22 19:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=15)),
                ('first_name', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=2)),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=10)),
                ('fax', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone', models.CharField(max_length=12)),
                ('company_name', models.CharField(max_length=35)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_fname', models.CharField(max_length=20)),
                ('emp_lname', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=4)),
                ('zip_code', models.CharField(max_length=9)),
                ('phone', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=1)),
                ('ss_number', models.CharField(max_length=11)),
                ('salary', models.FloatField(max_length=20)),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('termination_date', models.DateField(null=True)),
                ('birth_date', models.DateField(default=datetime.datetime.now)),
                ('bene_health_ins', models.CharField(max_length=1)),
                ('bene_life_ins', models.CharField(max_length=1)),
                ('bene_day_care', models.CharField(max_length=1)),
                ('sex', models.CharField(max_length=1)),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='FinCode',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('typeOf', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fin_code',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=18)),
                ('color', models.CharField(max_length=6)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField(max_length=15)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('region', models.CharField(max_length=7)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.customer')),
                ('fin_code_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.fincode')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.employee')),
            ],
            options={
                'db_table': 'sales_order',
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('ship_date', models.DateField()),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product')),
                ('sale_order_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.salesorder')),
            ],
            options={
                'db_table': 'sales_order_items',
            },
        ),
        migrations.CreateModel(
            name='FinData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4)),
                ('quarter', models.CharField(max_length=2)),
                ('amount', models.FloatField(max_length=9)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.fincode')),
            ],
            options={
                'db_table': 'fin_data',
            },
        ),
        migrations.CreateModel(
            name='EmpToDep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('termination_date', models.DateField(null=True)),
                ('ismanager', models.BooleanField(default=False)),
                ('departmentKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.department')),
                ('employeeKey', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.employee')),
            ],
        ),
        migrations.AddConstraint(
            model_name='salesorderitems',
            constraint=models.UniqueConstraint(fields=('sale_order_id', 'line_id'), name='sales_order_items_pk'),
        ),
        migrations.AddConstraint(
            model_name='findata',
            constraint=models.UniqueConstraint(fields=('year', 'quarter', 'code'), name='fin_data_pk'),
        ),
    ]
