# Generated by Django 3.1.7 on 2021-07-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210414_1404'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='salesorderitems',
            name='sales_order_items_pk',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='cust_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='fin_code_id',
            new_name='fin_code',
        ),
        migrations.RenameField(
            model_name='salesorderitems',
            old_name='prod_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='salesorderitems',
            old_name='sale_order_id',
            new_name='sale_order',
        ),
        migrations.AddConstraint(
            model_name='salesorderitems',
            constraint=models.UniqueConstraint(fields=('sale_order', 'line_id'), name='sales_order_items_pk'),
        ),
    ]
