# Generated by Django 3.1.2 on 2021-03-04 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forums', '0002_remove_forum_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='comments',
            field=models.ManyToManyField(related_name='forum_comments', through='forums.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
