version: "3.8"
services: 
    db:
        image: postgres
        volumes: 
            - ./data/db:/var/lib/postgresql/data
        environment: 
            - POSTGRES_DB=postgres_of_ormqueries_redis_celery
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        container_name: postgres_db

    app:
        build: .
        volumes: 
            - .:/django
        ports: 
            - 8000:8000
        image: django_pos_res_cel:django
        container_name: django_container_alpine_ormqueries_redis_celery
        command: python manage.py runserver 0.0.0.0:8000
        depends_on: 
            - db

    redis:
        image: redis:alpine
        container_name: redis

    celery:
        restart: always
        build:
            context: .
        command: celery -A ormQueries worker -l INFO
        volumes: 
            - .:/django
        container_name: celery
        depends_on: 
            - db
            - redis
            - app
    