# Generated by Django 3.1.2 on 2021-02-06 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('many', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='members',
        ),
        migrations.RemoveField(
            model_name='person',
            name='courses',
        ),
    ]
